# conda recipe

package:
  name: midas
  version: "1.1"

build:
  number: 1
  binary_relocation: true

source:
  # git_url: git://github.com/mjharriso/MIDAS.git
  fn: master.zip
  url: https://github.com/mjharriso/MIDAS/archive/master.zip

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - scipy
    - netcdf4
    - basemap
    - dateutil
test:
  imports:
    - midas.rectgrid
  commands:
    - echo "Testing from the meta.yaml"
    - echo "This is Windows" # [win]
    - echo "This is not Windows" # [not win]
    - echo "This is OSX" # [osx]
    - echo "This is not OSX" # [not osx]

about:
  home: https://github.com/mjharriso/MIDAS
  license: CreativeCommons 3.0
